### ISSUE TITLE
Map Info

### ISSUE THREAD

**Issue by Tommy-FF** [aleksn41/corona_world_app#42]
I could use an Info Box for World information -> bottom right corner maybe?
There I could display how much time passed since last reload of the map too. Maybe a button to reload manually?

**Comment by aleksn41** [comment]
An Info Box was planned but may only be implemented in screens with a big screen size as the Box may overlay too much of the map otherwise. This will only be implemented once issue #44 is resolved.
The User does not need to know how old his Data is since it is automatically refreshed every 15mins. And since 15 mins are a short time, no refresh Button is needed. This Issue will be opened if Issue #44 is closed.
